apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: transaction-file-generator
spec:
  schedule: "*/5 * * * *"
##schedule: "* */10 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: batch-file
              image: claudioed/transaction-file-generator
              env:
                - name: FROM_ACCOUNT
                  value: "1000"
                - name: TO_ACCOUNT
                  value: "100000"
                - name: OUT_FOLDER
                  value: /tmp/
              volumeMounts:
                - name: transaction-file-storage
                  mountPath: /tmp
          restartPolicy: OnFailure
          volumes:
            - name: transaction-file-storage
              persistentVolumeClaim:
                claimName: transaction-file-storage